    [0] = LAYOUT(
        QK_GESC,   KC_1,      KC_2,      KC_3,      KC_4,      KC_5,      KC_6,      KC_7,      KC_8,      KC_9,      KC_0,      KC_MINS,   KC_EQL,    KC_BSPC,   KC_INS,
        KC_TAB,    KC_Q,      KC_W,      KC_E,      KC_R,      KC_T,      KC_Y,      KC_U,      KC_I,      KC_O,      KC_P,      KC_LBRC,   KC_RBRC,   KC_BSLS,   KC_DEL,
        KC_CAPS,   KC_A,      KC_S,      KC_D,      KC_F,      KC_G,      KC_H,      KC_J,      KC_K,      KC_L,      KC_SCLN,   KC_QUOT,   KC_ENT,    KC_PGUP,
        KC_LSFT,   KC_Z,      KC_X,      KC_C,      KC_V,      KC_B,      KC_N,      KC_M,      KC_COMM,   KC_DOT,    KC_SLSH,   KC_RSFT,   KC_UP,     KC_PGDN,
        KC_LCTL,   KC_LGUI,   KC_LALT,   KC_SPC,    KC_RALT,   MO(1),     KC_LEFT,   KC_DOWN,   KC_RGHT,
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO
    ),
    [1] = LAYOUT(
        KC_GRV,    KC_F1,     KC_F2,     KC_F3,     KC_F4,     KC_F5,     KC_F6,     KC_F7,     KC_F8,     KC_F9,     KC_F10,    KC_F11,    KC_F12,    KC_DEL,    RL_MOD,
        KC_GRV,    KC_BT1,    KC_BT2,    KC_BT3,    KC_2G4,    KC_USB,    _______,   _______,   _______,   _______,   KC_PSCR,   KC_SCRL,   KC_PAUS,   RGB_MOD,   MUS_CUT,
        _______,   _______,   _______,   DEB_TOG,   _______,   SNAP_TOG,  _______,   _______,   _______,   _______,   KC_HOME,   KC_END,    RGB_HUI,   RL_VAI,
        _______,   _______,   _______,   _______,   _______,   _______,   NK_TOGG,   SYS_CUT,   KITT_SLOW, KITT_FAST, _______,   MO(4),     RGB_VAI,   RL_VAD,
        LED_TOG,   GAME_TOG,  HS_FREQ,   HS_BATQ,   LED_TOG,   _______,   RGB_SPD,   RGB_VAD,   RGB_SPI,
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO
    ),
    [2] = LAYOUT(
        QK_GESC,   KC_1,      KC_2,      KC_3,      KC_4,      KC_5,      KC_6,      KC_7,      KC_8,      KC_9,      KC_0,      KC_MINS,   KC_EQL,    KC_BSPC,   KC_INS,
        KC_TAB,    KC_Q,      KC_W,      KC_E,      KC_R,      KC_T,      KC_Y,      KC_U,      KC_I,      KC_O,      KC_P,      KC_LBRC,   KC_RBRC,   KC_BSLS,   KC_DEL,
        KC_CAPS,   KC_A,      KC_S,      KC_D,      KC_F,      KC_G,      KC_H,      KC_J,      KC_K,      KC_L,      KC_SCLN,   KC_QUOT,   KC_ENT,    KC_PGUP,
        KC_LSFT,   KC_Z,      KC_X,      KC_C,      KC_V,      KC_B,      KC_N,      KC_M,      KC_COMM,   KC_DOT,    KC_SLSH,   KC_RSFT,   KC_UP,     KC_PGDN,
        KC_LCTL,   MO(3),     KC_LALT,   KC_SPC,    KC_RGUI,   MO(3),     KC_LEFT,   KC_DOWN,   KC_RGHT,
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO
    ),
    [3] = LAYOUT(
        KC_GRV,    KC_F1,     KC_F2,     KC_F3,     KC_F4,     KC_F5,     KC_F6,     KC_F7,     KC_F8,     KC_F9,     KC_F10,    KC_F11,    KC_F12,    KC_DEL,    RL_MOD,
        KC_GRV,    KC_BT1,    KC_BT2,    KC_BT3,    KC_2G4,    KC_USB,    _______,   _______,   _______,   _______,   KC_PSCR,   KC_SCRL,   KC_PAUS,   RGB_MOD,   MUS_CUT,
        _______,   _______,   _______,   DEB_TOG,   _______,   SNAP_TOG,  _______,   _______,   _______,   _______,   KC_HOME,   KC_END,    RGB_HUI,   RL_VAI,
        _______,   _______,   _______,   _______,   _______,   _______,   NK_TOGG,   SYS_CUT,   KITT_SLOW, KITT_FAST, _______,   MO(4),     RGB_VAI,   RL_VAD,
        LED_TOG,   GAME_TOG,  HS_FREQ,   HS_BATQ,   LED_TOG,   _______,   RGB_SPD,   RGB_VAD,   RGB_SPI,
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO
    ),
    [4] = LAYOUT(
        QK_BOOT,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,
        _______,   _______,   BT_TEST,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,
        _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   KC_TEST,   _______,   _______,   _______,   _______,
        _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,
        _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,   _______,
        KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO,     KC_NO
    ),
